/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutilsRouteImport } from './routes/outils'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as OutilsSlugRouteImport } from './routes/outils.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as OutilsDiscoveredIdRouteImport } from './routes/outils.discovered.$id'
import { Route as AuthenticatedAdminDiscoveryRouteImport } from './routes/_authenticated/admin.discovery'
import { Route as ApiPublicCronDiscoveryRouteImport } from './routes/api.public.cron.discovery'

const OutilsRoute = OutilsRouteImport.update({
  id: '/outils',
  path: '/outils',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsSlugRoute = OutilsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OutilsRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsDiscoveredIdRoute = OutilsDiscoveredIdRouteImport.update({
  id: '/discovered/$id',
  path: '/discovered/$id',
  getParentRoute: () => OutilsRoute,
} as any)
const AuthenticatedAdminDiscoveryRoute =
  AuthenticatedAdminDiscoveryRouteImport.update({
    id: '/admin/discovery',
    path: '/admin/discovery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronDiscoveryRoute = ApiPublicCronDiscoveryRouteImport.update({
  id: '/api/public/cron/discovery',
  path: '/api/public/cron/discovery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/outils': typeof OutilsRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/outils/$slug': typeof OutilsSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/admin/discovery': typeof AuthenticatedAdminDiscoveryRoute
  '/outils/discovered/$id': typeof OutilsDiscoveredIdRoute
  '/api/public/cron/discovery': typeof ApiPublicCronDiscoveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/outils': typeof OutilsRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/outils/$slug': typeof OutilsSlugRoute
  '/categories': typeof CategoriesIndexRoute
  '/admin/discovery': typeof AuthenticatedAdminDiscoveryRoute
  '/outils/discovered/$id': typeof OutilsDiscoveredIdRoute
  '/api/public/cron/discovery': typeof ApiPublicCronDiscoveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/outils': typeof OutilsRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/outils/$slug': typeof OutilsSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/_authenticated/admin/discovery': typeof AuthenticatedAdminDiscoveryRoute
  '/outils/discovered/$id': typeof OutilsDiscoveredIdRoute
  '/api/public/cron/discovery': typeof ApiPublicCronDiscoveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/outils'
    | '/categories/$slug'
    | '/outils/$slug'
    | '/categories/'
    | '/admin/discovery'
    | '/outils/discovered/$id'
    | '/api/public/cron/discovery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/outils'
    | '/categories/$slug'
    | '/outils/$slug'
    | '/categories'
    | '/admin/discovery'
    | '/outils/discovered/$id'
    | '/api/public/cron/discovery'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/auth'
    | '/outils'
    | '/categories/$slug'
    | '/outils/$slug'
    | '/categories/'
    | '/_authenticated/admin/discovery'
    | '/outils/discovered/$id'
    | '/api/public/cron/discovery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  OutilsRoute: typeof OutilsRouteWithChildren
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ApiPublicCronDiscoveryRoute: typeof ApiPublicCronDiscoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/outils': {
      id: '/outils'
      path: '/outils'
      fullPath: '/outils'
      preLoaderRoute: typeof OutilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/$slug': {
      id: '/outils/$slug'
      path: '/$slug'
      fullPath: '/outils/$slug'
      preLoaderRoute: typeof OutilsSlugRouteImport
      parentRoute: typeof OutilsRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/discovered/$id': {
      id: '/outils/discovered/$id'
      path: '/discovered/$id'
      fullPath: '/outils/discovered/$id'
      preLoaderRoute: typeof OutilsDiscoveredIdRouteImport
      parentRoute: typeof OutilsRoute
    }
    '/_authenticated/admin/discovery': {
      id: '/_authenticated/admin/discovery'
      path: '/admin/discovery'
      fullPath: '/admin/discovery'
      preLoaderRoute: typeof AuthenticatedAdminDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/discovery': {
      id: '/api/public/cron/discovery'
      path: '/api/public/cron/discovery'
      fullPath: '/api/public/cron/discovery'
      preLoaderRoute: typeof ApiPublicCronDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDiscoveryRoute: typeof AuthenticatedAdminDiscoveryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDiscoveryRoute: AuthenticatedAdminDiscoveryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OutilsRouteChildren {
  OutilsSlugRoute: typeof OutilsSlugRoute
  OutilsDiscoveredIdRoute: typeof OutilsDiscoveredIdRoute
}

const OutilsRouteChildren: OutilsRouteChildren = {
  OutilsSlugRoute: OutilsSlugRoute,
  OutilsDiscoveredIdRoute: OutilsDiscoveredIdRoute,
}

const OutilsRouteWithChildren =
  OutilsRoute._addFileChildren(OutilsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  OutilsRoute: OutilsRouteWithChildren,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ApiPublicCronDiscoveryRoute: ApiPublicCronDiscoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
